# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-26 06:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dollar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='data')),
                ('value', models.DecimalField(decimal_places=3, max_digits=4, verbose_name='valor')),
            ],
        ),
        migrations.CreateModel(
            name='Euro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='data')),
                ('value', models.DecimalField(decimal_places=3, max_digits=4, verbose_name='valor')),
            ],
        ),
    ]
