# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-26 06:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50, unique=True, verbose_name='categoria')),
            ],
            options={
                'verbose_name_plural': 'categorias',
                'ordering': ['category'],
                'verbose_name': 'categoria',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='nome')),
            ],
            options={
                'verbose_name_plural': 'clientes',
                'ordering': ['name'],
                'verbose_name': 'cliente',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=60, unique=True, verbose_name='Produto')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Preço')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Category', verbose_name='categoria')),
            ],
            options={
                'verbose_name_plural': 'produtos',
                'ordering': ['product'],
                'verbose_name': 'produto',
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modificado em')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Customer', verbose_name='cliente')),
            ],
            options={
                'verbose_name_plural': 'vendas',
                'verbose_name': 'venda',
            },
        ),
        migrations.CreateModel(
            name='SaleDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(verbose_name='quantidade')),
                ('price_sale', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='preço de venda')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Product', verbose_name='produto')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Sale', verbose_name='venda')),
            ],
        ),
        migrations.AlterModelOptions(
            name='dollar',
            options={'ordering': ['date'], 'verbose_name': 'dólar', 'verbose_name_plural': 'dólares'},
        ),
        migrations.AlterModelOptions(
            name='euro',
            options={'ordering': ['date'], 'verbose_name': 'euro', 'verbose_name_plural': 'euros'},
        ),
    ]
